[target.aarch64-unknown-linux-gnu]
dockerfile = "./ci/Dockerfile"

[target.aarch64-unknown-linux-musl]
dockerfile = "./ci/Dockerfile"

[target.x86_64-pc-windows-gnu]
dockerfile = "./ci/Dockerfile"

[target.x86_64-unknown-freebsd]
dockerfile = "./ci/Dockerfile"

[target.x86_64-unknown-linux-gnu]
dockerfile = "./ci/Dockerfile"

[target.x86_64-unknown-linux-musl]
dockerfile = "./ci/Dockerfile"
