name: release

on:
  release:
    types: [published]

env:
  CROSS_VERSION: "0.2.5"
  GO_VERSION: "1.24.4"
  RUST_VERSION: "1.88.0"

jobs:
  release:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    env:
      ASSET: ""
      CARGO: cargo
    strategy:
      matrix:
        build:
          - freebsd-x86_64
          - linux-arm64
          - linux-x86_64
          - macos-arm64
          - macos-x86_64
        include:
          - build: freebsd-x86_64
            os: ubuntu-22.04
            target: x86_64-unknown-freebsd
          - build: linux-arm64
            os: ubuntu-22.04
            target: aarch64-unknown-linux-gnu
          - build: linux-x86_64
            os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - build: macos-x86_64
            os: macos-14
            target: x86_64-apple-darwin
          - build: macos-arm64
            os: macos-14
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        if: ${{ matrix.os != 'ubuntu-22.04' }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          target: ${{ matrix.target }}

      - name: Install cross
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: |
          ./ci/install-cross.sh
          echo "CARGO=cross" >> $GITHUB_ENV

      - name: Rust cargo build
        run: ${{ env.CARGO }} build --release --locked --target ${{ matrix.target }}

      - name: Build archive
        shell: bash
        run: |
          staging="metafmt-${{ github.ref_name }}-${{ matrix.target }}"
          cp "target/${{ matrix.target }}/release/metafmt" metafmt
          tar czf "$staging.tar.gz" metafmt
          echo "ASSET=$staging.tar.gz" >> $GITHUB_ENV

      - name: Upload release archive
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ github.ref_name }} ${{ env.ASSET }}
